#!/usr/bin/env bash
function clamp {
	min=$1
	max=$2
	val=$3
	python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2

if [[ "$direction" == "down" ]]; then
    delta=1
elif [[ "$direction" == "up" ]]; then
    delta=-1
else
    exit 0
fi

target=$(clamp 1 10 $((current + delta)))

echo "jumping to $target"
hyprctl dispatch "hl.dsp.focus({ workspace = $target })"
