#!/bin/bash

# get current active key-layout
#hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap'

# socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
# 	stdbuf -o0 awk -F '>>|,' -e '/^activelayout>>/ {print $3}' -e '/^focusedmon>>/ {print $3}'

# socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
# 	stdbuf -o0 awk -F '>>|,' '
#     /^activelayout>>/ {
#         if ($3 == "English (US)") {
#             system("hyprctl notify 1 3000 0 \"Keyboard: English (US)\"")
#         } else if ($3 == "Serbian") {
#             system("hyprctl notify 1 3000 0 \"Keyboard: Serbian\"")
#         }
#         print $3
#     }
#     /^focusedmon>>/ {print $3}
#     '

eww update var_key_layout="English (US)"

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - \
| stdbuf -o0 awk -F '>>|,' '
/^activelayout>>/ {
    pretty = $3
    short = pretty

    system("hyprctl notify 0 3000 0 \"Keyboard: " pretty "\"")
    print short
    fflush()
}
/^focusedmon>>/ {
    print $3
    fflush()
}
'
