#!/usr/bin/env bash

source ./notify

function get_volume_status() {
	vol=$(pamixer --get-volume)
	muted=$(pamixer --get-mute)

	if "$muted"; then
		echo "muted"
	else
		echo "$vol"
	fi
}

# Send initial value
get_volume_status

# Then listen for changes
pactl subscribe | grep --line-buffered "sink" | while read -r event; do
	get_volume_status
done
