#!/bin/sh
while read file; do
    case "$1" in
        "C-r")
            # Lossless rotation for JPEG files using jpegtran
            jpegtran -rotate 90 -copy all "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
            ;;
    esac
done
