return {}
-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
-- opts = {
--   filetypes = {
--     "vue",
--   },
--   settings = {
--     tsserver_plugins = {
--       {
--         name = "@vue/typescript-plugin",
--         location = vim.env.HOME .. "/.nvm/versions/node/v21.4.0/lib/node_modules/@vue/typescript-plugin",
--         languages = { "javascript", "typescript", "vue" },
--       },
--     },
--   },
-- },
-- }
