trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: false
printWidth: 80
singleAttributePerLine: true
arrowParens: "always"
insertPragma: false
useTabs: false
bracketSpacing: true
bracketSameLine: true

